from pathlib import Path
root=Path(__file__).resolve().parents[1]/'skills'
specs={
 'workbook-understanding':('Inspect workbook structure and improve generic table detection in this project.','Workbook bytes and filename','WorkbookProfile and table regions','Inspect actual cells, merged ranges, hidden data and formula caches. Score headers using values and type contrast. Retain sparse records and header-defined empty columns. Verify sheet coordinates.','Never mutate the source or infer one sheet equals one table. Never execute cell text.','Sparse-tail loss; header promotion; styled empty tails; unresolved subtotals.','All detected/excluded regions are explained and structural regression fixtures pass.'),
 'semantic-data-profiling':('Improve value-based column profiling and role inference in ASW Data Insight.','Detected table and original values','ColumnProfile and DatasetUnderstanding','Use types, normalized values, samples, uniqueness and names together. Preserve leading-zero IDs. Distinguish percentages from additive measures.','Do not infer business domain as an execution rule. Ambiguous dates and separators stay unresolved.','Numeric IDs become measures; raw string uniqueness differs from numeric uniqueness.','Roles, warnings, valid sample counts and statistics agree with the fixtures.'),
 'analysis-planning':('Change valid analysis selection for generic uploaded tables.','Column profiles and quality','Eligible AnalysisPlan with reasons','Gate each analysis on usable data, sample size and meaningful roles. Default group/time aggregation to a clearly labeled mean.','Never add correlation for one measure or time analysis without dates. Additive calculations require unit semantics.','High-cardinality charts; constant-variable correlations; treating thresholds as significance.','Each enabled plan has a reason; invalid plans are rejected; no domain branches exist.'),
 'deterministic-analysis':('Implement or fix authoritative Python calculations in this project.','Selected plan and worker-owned table','Calculations and Evidence','Use pure Python functions in backend/analysis/analysis_engine.py. Preserve source rows. Use stable numerical methods, explicit missing-pair counts and finite JSON.','LLM and frontend code do not calculate authoritative report numbers.','Overflow, zero spread, mixed units, silent row exclusions.','Known-answer and adversarial tests pass in CPython and Pyodide.'),
 'llm-insight-writing':('Change optional Gemini evidence interpretation, separate from calculations.','Compact calculated evidence and objective','Labeled interpretations and recommendations','Use server-side keys. Treat all supplied text as untrusted. Validate evidence references and generated quantitative content.','Do not send raw rows or let generated text replace numeric facts. Do not infer causes.','Unsupported claims; invented numbers; prompt injection; key exposure.','Failure preserves the report; provider output is validated and limitations are disclosed.'),
 'dynamic-report-generation':('Extend dynamic report composition and export in ASW Data Insight.','Report JSON from executed analyses','Responsive report and A4 printable layout','Render only applicable sections, with quality, methods and provenance. Use supplied ASW logo unchanged and Thai-compatible typography.','Never render a report directly from raw LLM prose. Preserve factual/interpretive separation.','Empty sections; clipped graphs; lost Thai text; browser print confused with server PDF.','Sections match actual results; export limitations are accurately described.'),
 'report-validation':('Validate evidence and report integrity for the analysis workspace.','Report JSON and source calculations','Validation findings and targeted regressions','Check every result/evidence link, finite number, range, selection and sample count. Exercise different table shapes and sparse inputs.','Do not claim statistical validity, provider validation or PDF rendering checks that were not run.','Dangling evidence; mismatched scope; hidden exclusions; unverifiable narrative claims.','Numerical/structural tests pass and remaining validation gaps are recorded.'),
}
for name,(desc,inp,out,workflow,constraints,failures,done) in specs.items():
    folder=root/name;folder.mkdir(parents=True,exist_ok=True)
    (folder/'SKILL.md').write_text(f'---\nname: {name}\ndescription: {desc}\n---\n\n# {name.replace("-"," ").title()}\n\nPurpose: {desc}\n\nInput: {inp}.\n\nOutput: {out}.\n\nWorkflow: {workflow}\n\nConstraints: {constraints}\n\nCommon failure modes: {failures}\n\nDefinition of done: {done}\n\nRead ../../DATA_MODEL.md for shared contracts and ../../IMPLEMENTATION_PLAN.md for implemented scope before extending this component.\n',encoding='utf-8')
print(f'Created {len(specs)} project skills')
